name: Node CI
on:
  push:
    branches: [master]
  pull_request:
    types: [opened, reopened]
jobs:
  build:
    name: Build and deploy Storybook
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    env:
      NODE_ENV: test
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install, lint, and test
      run: |
        yarn
        yarn lint
        yarn test
    - name: Build storybook
      run: |
        yarn storybook:build
    - name: Build website
      run: |
        yarn build
      env:
        CI: true
