name: Node CI
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    env:
      NODE_ENV: test
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install, lint, and test
      run: |
        npm ci
        npm run lint
        npm run test
    - name: Build storybook
      run: |
        npm run build
    - name: Build website
      run: |
        npm run build
      env:
        CI: true
